name: Build Bazzite ISO
on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build:
    name: Build ISO
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: true
      matrix:
        # On limite à 'bazzite' seul pour éviter la saturation mémoire (Erreur 125)
        image: [bazzite] 
    
    steps:
      - uses: actions/checkout@v4

      - name: Build Image and ISO
        run: |
          # Appel du script officiel de construction de Bazzite
          # Ce script génère l'image conteneur ET l'ISO
          ./build.sh ${{ matrix.image }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bazzite-iso-${{ matrix.image }}
          # On cherche tous les fichiers .iso générés dans le dossier
          path: "*.iso"
          if-no-files-found: error
